version: "3.8"

volumes:
  app_files:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/www
      o: bind

networks:
  default:
    name: ${APP_NAME}-network
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - app_files:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - default

  php-fpm:
    build: ./docker/php
    image: ${APP_NAME}-php
    container_name: ${APP_NAME}-php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - app_files:/var/www
    networks:
      - default

  mariadb:
    image: mariadb
    container_name: ${APP_NAME}-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb/dump:/docker-entrypoint-initdb.d
      - ./docker/mariadb/data:/var/lib/mysql
    networks:
      - default

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-dbadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - 8080:80
    depends_on:
      - mariadb
    networks:
      - default
